-- MySQL Script generated by MySQL Workbench
-- Sun May 25 15:51:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tecno-computer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tecno-computer` ;

-- -----------------------------------------------------
-- Schema tecno-computer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecno-computer` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tecno-computer` ;

-- -----------------------------------------------------
-- Table `tecno-computer`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`clientes` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`clientes` (
  `cliente_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `street_address` VARCHAR(100) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `registration_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `account_status` VARCHAR(20) NULL DEFAULT 'active',
  `notes` TEXT NULL DEFAULT NULL,
  `contact_preferences` VARCHAR(50) NULL DEFAULT NULL,
  `referred_by` VARCHAR(50) NULL DEFAULT NULL,
  `customer_type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `email` ON `tecno-computer`.`clientes` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecno-computer`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`departamentos` (
  `departamento_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT 'activo',
  PRIMARY KEY (`departamento_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecno-computer`.`maestro_categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`maestro_categorias` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`maestro_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecno-computer`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`inventario` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`inventario` (
  `id` INT NOT NULL,
  `id_maestro_categoria` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `valorCompra` VARCHAR(45) NULL DEFAULT NULL,
  `valorVenta` VARCHAR(45) NULL DEFAULT NULL,
  `fechaIngreso` DATETIME NULL DEFAULT NULL,
  `fechaActualizacion` DATETIME NULL DEFAULT NULL,
  `fechaSalida` DATETIME NULL DEFAULT NULL,
  `inventariocol` VARCHAR(45) NULL DEFAULT NULL,
  `enStock` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `serial` VARCHAR(45) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `masterCategory`
    FOREIGN KEY (`id_maestro_categoria`)
    REFERENCES `tecno-computer`.`maestro_categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `masterCategory_idx` ON `tecno-computer`.`inventario` (`id_maestro_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecno-computer`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'activo',
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `email_UNIQUE` ON `tecno-computer`.`usuarios` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecno-computer`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`tickets` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`tickets` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `departamento_id` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `prioridad` VARCHAR(20) NOT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  `ultimo_comentario` TEXT NULL DEFAULT NULL,
  `tiempo_resolucion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ticket_id`),
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tecno-computer`.`ordenes_servicio` (`idordenes_servicio`)
    ON DELETE SET NULL,
  CONSTRAINT `tickets_ibfk_2`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `tecno-computer`.`departamentos` (`departamento_id`),
  CONSTRAINT `tickets_ibfk_3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tecno-computer`.`usuarios` (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `departamento_id` ON `tecno-computer`.`tickets` (`departamento_id` ASC) VISIBLE;

CREATE INDEX `usuario_id` ON `tecno-computer`.`tickets` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `idx_tickets_orden` ON `tecno-computer`.`tickets` (`orden_id` ASC) VISIBLE;

CREATE INDEX `idx_tickets_estado` ON `tecno-computer`.`tickets` (`estado` ASC) VISIBLE;

CREATE INDEX `idx_tickets_prioridad` ON `tecno-computer`.`tickets` (`prioridad` ASC) VISIBLE;

CREATE INDEX `idx_tickets_fecha` ON `tecno-computer`.`tickets` (`fecha_creacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecno-computer`.`ordenes_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`ordenes_servicio` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`ordenes_servicio` (
  `idordenes_servicio` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `serial` VARCHAR(45) NULL DEFAULT NULL,
  `diag_inicial` VARCHAR(500) NULL DEFAULT NULL,
  `diag_final` VARCHAR(500) NULL DEFAULT NULL,
  `serial_ram_1` VARCHAR(45) NULL DEFAULT NULL,
  `serial_ram_2` VARCHAR(45) NULL DEFAULT NULL,
  `serial_disco_1` VARCHAR(45) NULL DEFAULT NULL,
  `serial_disco_2` VARCHAR(45) NULL DEFAULT NULL,
  `serial_cargador` VARCHAR(45) NULL DEFAULT NULL,
  `serial_bateria` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_entrada` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_salida` DATETIME NULL DEFAULT NULL,
  `id_cliente` BIGINT NULL DEFAULT NULL,
  `inicio_trabajo` DATETIME NULL DEFAULT NULL,
  `fin_trabajo` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `id_tecnico` VARCHAR(45) NULL DEFAULT NULL,
  `ticket_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idordenes_servicio`),
  CONSTRAINT `fk_orden_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `tecno-computer`.`tickets` (`ticket_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de órdenes de servicio con soporte para tickets de seguimiento';

CREATE INDEX `idx_orden_ticket` ON `tecno-computer`.`ordenes_servicio` (`ticket_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecno-computer`.`ticket_comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecno-computer`.`ticket_comentarios` ;

CREATE TABLE IF NOT EXISTS `tecno-computer`.`ticket_comentarios` (
  `comentario_id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `comentario` TEXT NOT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comentario_id`),
  CONSTRAINT `ticket_comentarios_ibfk_1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `tecno-computer`.`tickets` (`ticket_id`)
    ON DELETE CASCADE,
  CONSTRAINT `ticket_comentarios_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tecno-computer`.`usuarios` (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ticket_id` ON `tecno-computer`.`ticket_comentarios` (`ticket_id` ASC) VISIBLE;

CREATE INDEX `usuario_id` ON `tecno-computer`.`ticket_comentarios` (`usuario_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
